[package]
name = "rust-tree"
version = "0.1.0"
authors = ["Johnathan Walker <johnathan.walker23832@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"